inherit: configs/baseline.yaml

rl:
  algo: lagrangian_ppo
  steps: 64
  gamma: 0.99
  lr: 3.0e-4
  ent_coef: 0.01
  batch_size: 128
  n_steps: 64
  clip_range: 0.2
  vf_coef: 0.5
  max_grad_norm: 0.5
  safety:
    latency_max_ms: 5.0
    compute_max: 1.0e9
    mask_actions: true
controller_actions:
  W: [3,5,7,9]
  F: [1,2]
  iters: [8,12,16,20,24]
  damp: [0.2,0.4,0.6,0.8]
  schedule: ["flooding","layered"]
eval:
  frames: 200
logdir: ./data/logs/saferl_quick
