# Baseline (fixed-parameter) sliding-window decoding
code:
  family: CSS-QLDPC
  N: 1000
  params: {w: 3, L: 25, Z: 127}
channel:
  type: quantum_mixed_timevarying
  seed: 1
  depolar: 0.005
  dephase: 0.01
  erasure: 0.02
  meas_err: 0.001
  burst:
    model: markov_two_state
    p_on: 0.02
    p_off: 0.1
    strength: 3.0
    drift: 0.0001
decoder:
  algorithm: bp_min_sum
  window:
    W: 5
    F: 1
  iters: 20
  damping: 0.5
  schedule: layered
eval:
  frames: 20
  latency_budget_ms: 5.0
  compute_budget: 1.0e9
logdir: ./data/logs/baseline
