# SafeRL-Window controller with Lagrangian-PPO
inherit: configs/baseline.yaml

rl:
  algo: lagrangian_ppo
  steps: 200000
  gamma: 0.99
  lr: 3.0e-4
  ent_coef: 0.01
  batch_size: 4096
  n_steps: 2048
  clip_range: 0.2
  vf_coef: 0.5
  max_grad_norm: 0.5
  safety:
    latency_max_ms: 5.0
    compute_max: 1.0e9
    mask_actions: true
    fallback_on_low_conf: true
    conf_threshold: 0.2
controller_actions:
  W: [3,5,7,9]
  F: [1,2]
  iters: [8,12,16,20,24]
  damping: [0.2,0.4,0.6,0.8]
  schedule: ["flooding","layered"]
eval:
  frames: 2000
logdir: ./data/logs/saferl
