code:
  name: repetition
  distances: [3, 5, 7]

noise_model: bit_flip
decoder: analog

p_range:
  min: 1.0e-4
  max: 1.0e-1
  points: 13

shots: 10000
rounds: 1

readout:
  sigma: 0.25

# nonzero leakage stress test
leakage: 0.02
