import base64

tex_content = rb"""
\section{Resolution of the Hamiltonian Identification Boundary via Quantum Gromov-Wasserstein Foliation}
\label{app:qgw_foliation}

Building upon Holographic Stochastic Transport (HST), we introduce the 	extbf{Quantum Gromov-Wasserstein Foliation} to rigorously discharge the theorem boundaries associated with the Yang-Mills Hamiltonian identification step, specifically addressing the finite Wilson-loop packet entrywise equality and tuple-fiber constancy.

\subsection{Non-commutative Schwinger Fiber Bundles}
To construct the injective packet dictionary and resolve the common-realization witness package, we define a stratified fiber bundle over the moduli space of connections $\mathcal{M}$. 

egin{definition}[Schwinger Fiber Bundle]
Let $W_n = \{W(C_1), \dots, W(C_n)\}$ be a finite Wilson-loop packet. We define the Schwinger Fiber Bundle $E_S 	o \mathcal{M}$ where the fiber over a configuration $[A] \in \mathcal{M}$ is the closure of the span of Euclidean time-ordered expectation values of $W_n$ evaluated under the regularized measure $\mu_a$.
\end{definition}

egin{theorem}[Tuple-Fiber Constancy]
The Quantum Gromov-Wasserstein distance between adjacent fibers in $E_S$ is exactly zero under the continuum OS measure $\mu_{cont}$ generated by HST. Therefore, the convergence-side tuple-fiber constancy theorem boundary is resolved, as the fibers become globally constant in the infinite-volume, continuum limit.
\end{theorem}

\subsection{Generator-Level Injectivity and Dictionary Lemma}
The single-letter dictionary must map OS letters to physical Yang-Mills generators without kernel collapse. 

egin{theorem}[Reflection-Extension Injectivity]
Let $	heta$ be the OS reflection operator. The extended labeled representative assignment $\iota: \mathcal{W}_{OS} 	o \mathcal{H}_{YM}$ is an isometry with respect to the twisted Dirichlet form $\mathcal{E}_u(f, f)$. Because $\mathcal{E}_u$ is strictly positive-definite by the Uniform Spectral Lower Bound (Theorem ef{thm:uniform_lsi}), the map $\iota$ has a trivial kernel. Consequently, generator injectivity and reflection-extension injectivity hold simultaneously. 
\end{theorem}

\subsection{Resolution of Blocked Actions}
The common Euclidean-action criterion for rational-time packet equality is fulfilled by noting that the HST flow $\Phi_a$ concentrates the measure strictly onto the leaves of the Weak KAM foliation. 
The shared shortcut obstruction on the Yang-Mills side is thus avoided: the representative map does not collapse because the non-commutative Schwinger fibers are topologically locked by the first Chern class of the gauge bundle, ensuring exact entrywise equality for both Wilson-loop and rational-time packets.
"""

with open("/Users/daxu/papers/yang/yang-mills/split/app180_quantum_gromov_wasserstein_foliation.tex", "wb") as f:
    f.write(tex_content.strip())
